# Generated by Django 3.1.6 on 2021-02-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_post_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('TC', 'Technology'), ('BG', 'Bugs'), ('MN', 'Money'), ('NA', 'Select one category')], default='TC', max_length=2),
        ),
    ]
