# Generated by Django 3.1.6 on 2021-02-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
